version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - MODEL_PATH=${MODEL_PATH}
      - VECTOR_STORE_DIR=/app/data/vector_store
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
